#!/bin/sh

header(){
echo "****************************************************************************************************"
echo "****************************************************************************************************"
echo "**                                                                                                **"
while [ "$*" != "" ]
do
  printf "** %-94s **\n" "$1"
  shift
done
echo "**                                                                                                **"
echo "****************************************************************************************************"
}
footer(){
echo ""
echo ""
echo ""
}
divider(){
echo ""
echo "****************************************************************************************************"
printf "** %-94s **\n" "$1"
echo "****************************************************************************************************"
echo ""
}

#---------------------------------------------------------------------------------------------------------------
header "test_Al_FCCcohesive_MI_OPBC"       \
       "   |"                              \
       "   |-- model_Al_PF_ErcolessiAdams" \
       "   |"

divider "test_Al_FCCcohesive_MI_OPBC --- model_Al_PF_ErcolessiAdams"
echo model_Al_PF_ErcolessiAdams | ./test_Al_FCCcohesive_MI_OPBC/test_Al_FCCcohesive_MI_OPBC
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Al_free_cluster"              \
       "   |"                              \
       "   |-- model_Al_PF_ErcolessiAdams" \
       "   |"

divider "test_Al_free_cluster --- model_Al_PF_ErcolessiAdams"
echo model_Al_PF_ErcolessiAdams | ./test_Al_free_cluster/test_Al_free_cluster
footer


#---------------------------------------------------------------------------------------------------------------
header "test_ArNe_B2cohesive_NEIGH_RVEC"      \
       "   |"                                 \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |"

divider "test_ArNe_B2cohesive_NEIGH_RVEC --- model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F | ./test_ArNe_B2cohesive_NEIGH_RVEC/test_ArNe_B2cohesive_NEIGH_RVEC
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Ar_FCCcohesiveCutoff_NEIGH_RVEC" \
       "   |"                                 \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- model_Ar_P_MMorse"             \
       "   |"

divider "test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F | ./test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/test_Ar_FCCcohesiveCutoff_NEIGH_RVEC

divider "test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- model_Ar_P_MLJ_NEIGH_RVEC_F"
echo model_Ar_P_MLJ_NEIGH_RVEC_F   | ./test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/test_Ar_FCCcohesiveCutoff_NEIGH_RVEC

divider "test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse             | ./test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/test_Ar_FCCcohesiveCutoff_NEIGH_RVEC
footer

#---------------------------------------------------------------------------------------------------------------
header "test_Ar_FCCcohesive_MI_OPBC"        \
       "   |"                               \
       "   |-- model_Ar_P_MLJ_C"            \
       "   |-- model_Ar_P_MLJ_F90"          \
       "   |-- model_Ar_P_MLJ_MI_OPBC_H_F"  \
       "   |-- model_Ar_P_MMorse"           \
       "   |"

divider "test_Ar_FCCcohesive_MI_OPBC --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C           | ./test_Ar_FCCcohesive_MI_OPBC/test_Ar_FCCcohesive_MI_OPBC

divider "test_Ar_FCCcohesive_MI_OPBC --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90         | ./test_Ar_FCCcohesive_MI_OPBC/test_Ar_FCCcohesive_MI_OPBC

divider "test_Ar_FCCcohesive_MI_OPBC --- model_Ar_P_MLJ_MI_OPBC_H_F"
echo model_Ar_P_MLJ_MI_OPBC_H_F | ./test_Ar_FCCcohesive_MI_OPBC/test_Ar_FCCcohesive_MI_OPBC

divider "test_Ar_FCCcohesive_MI_OPBC --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse          | ./test_Ar_FCCcohesive_MI_OPBC/test_Ar_FCCcohesive_MI_OPBC
footer

#---------------------------------------------------------------------------------------------------------------
header "test_Ar_FCCcohesive_NEIGH_PURE"       \
       "   |"                                 \
       "   |-- model_Ar_P_MLJ_C"              \
       "   |-- model_Ar_P_MLJ_F90"            \
       "   |-- model_Ar_P_MLJ_NEIGH_PURE_H_F" \
       "   |-- model_Ar_P_MMorse"             \
       "   |"

divider "test_Ar_FCCcohesive_NEIGH_PURE --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C              | ./test_Ar_FCCcohesive_NEIGH_PURE/test_Ar_FCCcohesive_NEIGH_PURE

divider "test_Ar_FCCcohesive_NEIGH_PURE --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90            | ./test_Ar_FCCcohesive_NEIGH_PURE/test_Ar_FCCcohesive_NEIGH_PURE

divider "test_Ar_FCCcohesive_NEIGH_PURE --- model_Ar_P_MLJ_NEIGH_PURE_H_F"
echo model_Ar_P_MLJ_NEIGH_PURE_H_F | ./test_Ar_FCCcohesive_NEIGH_PURE/test_Ar_FCCcohesive_NEIGH_PURE

divider "test_Ar_FCCcohesive_NEIGH_PURE --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse             | ./test_Ar_FCCcohesive_NEIGH_PURE/test_Ar_FCCcohesive_NEIGH_PURE
footer

#---------------------------------------------------------------------------------------------------------------
header "test_Ar_FCCcohesive_NEIGH_RVEC"        \
       "   |"                                  \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F"  \
       "   |-- model_Ar_P_MLJ_C"               \
       "   |-- model_Ar_P_MLJ_F90"             \
       "   |-- model_Ar_P_MLJ_NEIGH_RVEC_F"    \
       "   |-- model_Ar_P_MMorse"              \
       "   |"

divider "test_Ar_FCCcohesive_NEIGH_RVEC --- model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F | ./test_Ar_FCCcohesive_NEIGH_RVEC/test_Ar_FCCcohesive_NEIGH_RVEC

divider "test_Ar_FCCcohesive_NEIGH_RVEC --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C              | ./test_Ar_FCCcohesive_NEIGH_RVEC/test_Ar_FCCcohesive_NEIGH_RVEC

divider "test_Ar_FCCcohesive_NEIGH_RVEC --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90            | ./test_Ar_FCCcohesive_NEIGH_RVEC/test_Ar_FCCcohesive_NEIGH_RVEC

divider "test_Ar_FCCcohesive_NEIGH_RVEC --- model_Ar_P_MLJ_NEIGH_RVEC_F"
echo model_Ar_P_MLJ_NEIGH_RVEC_F   | ./test_Ar_FCCcohesive_NEIGH_RVEC/test_Ar_FCCcohesive_NEIGH_RVEC

divider "test_Ar_FCCcohesive_NEIGH_RVEC --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse             | ./test_Ar_FCCcohesive_NEIGH_RVEC/test_Ar_FCCcohesive_NEIGH_RVEC
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Ar_free_cluster"                 \
       "   |"                                 \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- model_Ar_P_MLJ_C"              \
       "   |-- model_Ar_P_MLJ_F90"            \
       "   |-- model_Ar_P_MLJ_MI_OPBC_H_F"    \
       "   |-- model_Ar_P_MLJ_NEIGH_PURE_H_F" \
       "   |-- model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- model_Ar_P_MMorse"             \
       "   |"

divider "test_Ar_free_cluster --- model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C              | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90            | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MLJ_MI_OPBC_H_F"
echo model_Ar_P_MLJ_MI_OPBC_H_F    | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MLJ_NEIGH_PURE_H_F"
echo model_Ar_P_MLJ_NEIGH_PURE_H_F | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MLJ_NEIGH_RVEC_F"
echo model_Ar_P_MLJ_NEIGH_RVEC_F   | ./test_Ar_free_cluster/test_Ar_free_cluster

divider "test_Ar_free_cluster --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse             | ./test_Ar_free_cluster/test_Ar_free_cluster
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Ar_free_cluster_CLUSTER_C"    \
       "   |"                              \
       "   |-- model_Ar_P_MLJ_C"           \
       "   |-- model_Ar_P_MLJ_F90"         \
       "   |-- model_Ar_P_MLJ_CLUSTER_C"   \
       "   |-- model_Ar_P_MLJ_CLUSTER_F90" \
       "   |-- model_Ar_P_MMorse"          \
       "   |"

divider "test_Ar_free_cluster_CLUSTER_C --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C           | ./test_Ar_free_cluster_CLUSTER_C/test_Ar_free_cluster_CLUSTER_C

divider "test_Ar_free_cluster_CLUSTER_C --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90         | ./test_Ar_free_cluster_CLUSTER_C/test_Ar_free_cluster_CLUSTER_C

divider "test_Ar_free_cluster_CLUSTER_C --- model_Ar_P_MLJ_CLUSTER_C"
echo model_Ar_P_MLJ_CLUSTER_C   | ./test_Ar_free_cluster_CLUSTER_C/test_Ar_free_cluster_CLUSTER_C

divider "test_Ar_free_cluster_CLUSTER_C --- model_Ar_P_MLJ_CLUSTER_F90"
echo model_Ar_P_MLJ_CLUSTER_F90 | ./test_Ar_free_cluster_CLUSTER_C/test_Ar_free_cluster_CLUSTER_C

divider "test_Ar_free_cluster_CLUSTER_C --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse          | ./test_Ar_free_cluster_CLUSTER_C/test_Ar_free_cluster_CLUSTER_C
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Ar_free_cluster_CLUSTER_F90"  \
       "   |"                              \
       "   |-- model_Ar_P_MLJ_C"           \
       "   |-- model_Ar_P_MLJ_F90"         \
       "   |-- model_Ar_P_MLJ_CLUSTER_C"   \
       "   |-- model_Ar_P_MLJ_CLUSTER_F90" \
       "   |-- model_Ar_P_MMorse"          \
       "   |"

divider "test_Ar_free_cluster_CLUSTER_F90 --- model_Ar_P_MLJ_C"
echo model_Ar_P_MLJ_C           | ./test_Ar_free_cluster_CLUSTER_F90/test_Ar_free_cluster_CLUSTER_F90

divider "test_Ar_free_cluster_CLUSTER_F90 --- model_Ar_P_MLJ_F90"
echo model_Ar_P_MLJ_F90         | ./test_Ar_free_cluster_CLUSTER_F90/test_Ar_free_cluster_CLUSTER_F90

divider "test_Ar_free_cluster_CLUSTER_F90 --- model_Ar_P_MLJ_CLUSTER_C"
echo model_Ar_P_MLJ_CLUSTER_C   | ./test_Ar_free_cluster_CLUSTER_F90/test_Ar_free_cluster_CLUSTER_F90

divider "test_Ar_free_cluster_CLUSTER_F90 --- model_Ar_P_MLJ_CLUSTER_F90"
echo model_Ar_P_MLJ_CLUSTER_F90 | ./test_Ar_free_cluster_CLUSTER_F90/test_Ar_free_cluster_CLUSTER_F90

divider "test_Ar_free_cluster_CLUSTER_F90 --- model_Ar_P_MMorse"
echo model_Ar_P_MMorse          | ./test_Ar_free_cluster_CLUSTER_F90/test_Ar_free_cluster_CLUSTER_F90
footer

#---------------------------------------------------------------------------------------------------------------
header "test_Ar_multiple_models"              \
       "   |"                                 \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- model_Ar_P_MLJ_C"              \
       "   |-- model_Ar_P_MLJ_F90"            \
       "   |-- model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- model_Ar_P_MMorse"             \
       "   |"
echo ""
echo "NOTE: Only two examples are executed here because all other permutations produce identical results"
echo ""
divider "test_Ar_multiple_models --- model_ArNe_P_MLJ_NEIGH_RVEC_F -and- model_Ar_P_MLJ_C"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F model_Ar_P_MLJ_C | ./test_Ar_multiple_models/test_Ar_multiple_models

divider "test_Ar_multiple_models --- model_ArNe_P_MLJ_NEIGH_RVEC_F -and- model_Ar_P_MMorse"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F model_Ar_P_MMorse | ./test_Ar_multiple_models/test_Ar_multiple_models
footer


#---------------------------------------------------------------------------------------------------------------
header "test_Ne_free_cluster"                 \
       "   |"                                 \
       "   |-- model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- model_Ne_P_LJ_NEIGH_PURE_H"    \
       "   |-- model_Ne_P_MLJ_NEIGH_RVEC_F"   \
       "   |"

divider "test_Ne_free_cluster --- model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo model_ArNe_P_MLJ_NEIGH_RVEC_F  | ./test_Ne_free_cluster/test_Ne_free_cluster

divider "test_Ne_free_cluster --- model_Ne_P_LJ_NEIGH_PURE_H"
echo model_Ne_P_LJ_NEIGH_PURE_H     | ./test_Ne_free_cluster/test_Ne_free_cluster

divider "test_Ne_free_cluster --- model_Ne_P_MLJ_NEIGH_RVEC_F"
echo model_Ne_P_MLJ_NEIGH_RVEC_F    | ./test_Ne_free_cluster/test_Ne_free_cluster
footer
