#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2012, Regents of the University of Minnesota.  All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#    Ellad B. Tadmor
#

#
# Release: This file is part of the openkim-api.git repository.
#


# usage: run_all_ex_tests [filename]
#
# If `filename' is given each actual Test output will be redirected to a separate file.
# This option facilitates the comparison of Test results for different Models using
# `diff' or another comparison utility program.
#
# When the optional argument is given the output is put in a series of files with names
# filename.TEST_NUM.MODEL_NUM.  Here `filename' is the value provided on the command line,
# `TEST_NUM' is a two digit integer sequentially numbering the example Tests in the order
# they are executed below, and `MODEL_NUM' is a two digit integer sequentially numbering the
# Models that each Test is executed with in the order they are executed below.
#

TEST_NUM=0
MODEL_NUM=0
if test $# -gt 0; then
  redirect='$1.`printf "%02i" $TEST_NUM`.`printf "%02i" $MODEL_NUM`';
else
  redirect='1';
fi

header(){
echo "****************************************************************************************************"
echo "****************************************************************************************************"
echo "**                                                                                                **"
while [ "$*" != "" ]
do
  printf "** %-94s **\n" "$1"
  shift
done
echo "**                                                                                                **"
echo "****************************************************************************************************"
}
footer(){
echo ""
echo ""
echo ""
TEST_NUM=$(($TEST_NUM + 1))
MODEL_NUM=0
}
divider(){
echo ""
echo "****************************************************************************************************"
printf "** %-94s **\n" "$1"
echo "****************************************************************************************************"
echo ""
}

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Al_FCCcohesive_MI_OPBC"       \
       "   |"                                 \
       "   |-- ex_model_Al_PF_ErcolessiAdams" \
       "   |"

divider "ex_test_Al_FCCcohesive_MI_OPBC --- ex_model_Al_PF_ErcolessiAdams"
echo ex_model_Al_PF_ErcolessiAdams | ./ex_test_Al_FCCcohesive_MI_OPBC/ex_test_Al_FCCcohesive_MI_OPBC >&$redirect && B=$(($B + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_Al_free_cluster"              \
       "   |"                                 \
       "   |-- ex_model_Al_PF_ErcolessiAdams" \
       "   |"

divider "ex_test_Al_free_cluster --- ex_model_Al_PF_ErcolessiAdams"
echo ex_model_Al_PF_ErcolessiAdams | ./ex_test_Al_free_cluster/ex_test_Al_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_ArNe_B2cohesive_NEIGH_RVEC"      \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |"

divider "ex_test_ArNe_B2cohesive_NEIGH_RVEC --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F | ./ex_test_ArNe_B2cohesive_NEIGH_RVEC/ex_test_ArNe_B2cohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC" \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- ex_model_Ar_P_LJ"                 \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- ex_model_Ar_P_Morse"              \
       "   |"

divider "ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F | ./ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ                 | ./ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"
echo ex_model_Ar_P_MLJ_NEIGH_RVEC_F   | ./ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse              | ./ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC/ex_test_Ar_FCCcohesiveCutoff_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_FCCcohesive_MI_OPBC"        \
       "   |"                                  \
       "   |-- ex_model_Ar_P_LJ"               \
       "   |-- ex_model_Ar_P_MLJ_C"            \
       "   |-- ex_model_Ar_P_MLJ_F90"          \
       "   |-- ex_model_Ar_P_MLJ_MI_OPBC_H_F"  \
       "   |-- ex_model_Ar_P_Morse"            \
       "   |"

divider "ex_test_Ar_FCCcohesive_MI_OPBC --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ              | ./ex_test_Ar_FCCcohesive_MI_OPBC/ex_test_Ar_FCCcohesive_MI_OPBC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_MI_OPBC --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C           | ./ex_test_Ar_FCCcohesive_MI_OPBC/ex_test_Ar_FCCcohesive_MI_OPBC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_MI_OPBC --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90         | ./ex_test_Ar_FCCcohesive_MI_OPBC/ex_test_Ar_FCCcohesive_MI_OPBC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_MI_OPBC --- ex_model_Ar_P_MLJ_MI_OPBC_H_F"
echo ex_model_Ar_P_MLJ_MI_OPBC_H_F | ./ex_test_Ar_FCCcohesive_MI_OPBC/ex_test_Ar_FCCcohesive_MI_OPBC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_MI_OPBC --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse           | ./ex_test_Ar_FCCcohesive_MI_OPBC/ex_test_Ar_FCCcohesive_MI_OPBC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_FCCcohesive_NEIGH_PURE"       \
       "   |"                                    \
       "   |-- ex_model_Ar_P_LJ"                 \
       "   |-- ex_model_Ar_P_MLJ_C"              \
       "   |-- ex_model_Ar_P_MLJ_F90"            \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_PURE_H_F" \
       "   |-- ex_model_Ar_P_Morse"              \
       "   |"

divider "ex_test_Ar_FCCcohesive_NEIGH_PURE --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ                 | ./ex_test_Ar_FCCcohesive_NEIGH_PURE/ex_test_Ar_FCCcohesive_NEIGH_PURE >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_PURE --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C              | ./ex_test_Ar_FCCcohesive_NEIGH_PURE/ex_test_Ar_FCCcohesive_NEIGH_PURE >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_PURE --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90            | ./ex_test_Ar_FCCcohesive_NEIGH_PURE/ex_test_Ar_FCCcohesive_NEIGH_PURE >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_PURE --- ex_model_Ar_P_MLJ_NEIGH_PURE_H_F"
echo ex_model_Ar_P_MLJ_NEIGH_PURE_H_F | ./ex_test_Ar_FCCcohesive_NEIGH_PURE/ex_test_Ar_FCCcohesive_NEIGH_PURE >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_PURE --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse              | ./ex_test_Ar_FCCcohesive_NEIGH_PURE/ex_test_Ar_FCCcohesive_NEIGH_PURE >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_FCCcohesive_NEIGH_RVEC"        \
       "   |"                                     \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"  \
       "   |-- ex_model_Ar_P_LJ"                  \
       "   |-- ex_model_Ar_P_MLJ_C"               \
       "   |-- ex_model_Ar_P_MLJ_F90"             \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"    \
       "   |-- ex_model_Ar_P_Morse"               \
       "   |"

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ                 | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C              | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90            | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"
echo ex_model_Ar_P_MLJ_NEIGH_RVEC_F   | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_FCCcohesive_NEIGH_RVEC --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse              | ./ex_test_Ar_FCCcohesive_NEIGH_RVEC/ex_test_Ar_FCCcohesive_NEIGH_RVEC >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_free_cluster"                 \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- ex_model_Ar_P_LJ"                 \
       "   |-- ex_model_Ar_P_MLJ_C"              \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_C"      \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_F90"    \
       "   |-- ex_model_Ar_P_MLJ_F90"            \
       "   |-- ex_model_Ar_P_MLJ_MI_OPBC_H_F"    \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_PURE_H_F" \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- ex_model_Ar_P_Morse"              \
       "   |"

divider "ex_test_Ar_free_cluster --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ                 | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C              | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_CLUSTER_C"
echo ex_model_Ar_P_MLJ_CLUSTER_C      | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_CLUSTER_F90"
echo ex_model_Ar_P_MLJ_CLUSTER_F90    | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90            | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_MI_OPBC_H_F"
echo ex_model_Ar_P_MLJ_MI_OPBC_H_F    | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_NEIGH_PURE_H_F"
echo ex_model_Ar_P_MLJ_NEIGH_PURE_H_F | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"
echo ex_model_Ar_P_MLJ_NEIGH_RVEC_F   | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse              | ./ex_test_Ar_free_cluster/ex_test_Ar_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_free_cluster_CLUSTER_C"    \
       "   |"                                 \
       "   |-- ex_model_Ar_P_LJ"              \
       "   |-- ex_model_Ar_P_MLJ_C"           \
       "   |-- ex_model_Ar_P_MLJ_F90"         \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_C"   \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_F90" \
       "   |-- ex_model_Ar_P_Morse"           \
       "   |"

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ              | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C           | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90         | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_MLJ_CLUSTER_C"
echo ex_model_Ar_P_MLJ_CLUSTER_C   | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_MLJ_CLUSTER_F90"
echo ex_model_Ar_P_MLJ_CLUSTER_F90 | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_C --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse           | ./ex_test_Ar_free_cluster_CLUSTER_C/ex_test_Ar_free_cluster_CLUSTER_C >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer


#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_free_cluster_CLUSTER_F90"  \
       "   |"                                 \
       "   |-- ex_model_Ar_P_LJ"              \
       "   |-- ex_model_Ar_P_MLJ_C"           \
       "   |-- ex_model_Ar_P_MLJ_F90"         \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_C"   \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_F90" \
       "   |-- ex_model_Ar_P_Morse"           \
       "   |"

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ              | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C           | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_MLJ_F90"
echo ex_model_Ar_P_MLJ_F90         | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_MLJ_CLUSTER_C"
echo ex_model_Ar_P_MLJ_CLUSTER_C   | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_MLJ_CLUSTER_F90"
echo ex_model_Ar_P_MLJ_CLUSTER_F90 | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_F90 --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse           | ./ex_test_Ar_free_cluster_CLUSTER_F90/ex_test_Ar_free_cluster_CLUSTER_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_free_cluster_CLUSTER_memory_F90"  \
       "   |"                                 \
       "   |-- ex_model_Ar_P_LJ"              \
       "   |-- ex_model_Ar_P_MLJ_C"           \
       "   |-- ex_model_Ar_P_MLJ_F90"         \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_C"   \
       "   |-- ex_model_Ar_P_MLJ_CLUSTER_F90" \
       "   |-- ex_model_Ar_P_Morse"           \
       "   |"

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_LJ              | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_MLJ_C"
echo ex_model_Ar_P_MLJ_C           | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_MLJ_memory_F90"
echo ex_model_Ar_P_MLJ_memory_F90         | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_MLJ_CLUSTER_C"
echo ex_model_Ar_P_MLJ_CLUSTER_C   | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_MLJ_CLUSTER_memory_F90"
echo ex_model_Ar_P_MLJ_CLUSTER_memory_F90 | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_free_cluster_CLUSTER_memory_F90 --- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_Morse           | ./ex_test_Ar_free_cluster_CLUSTER_memory_F90/ex_test_Ar_free_cluster_CLUSTER_memory_F90 >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ar_multiple_models"              \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- ex_model_Ar_P_LJ"                 \
       "   |-- ex_model_Ar_P_MLJ_C"              \
       "   |-- ex_model_Ar_P_MLJ_F90"            \
       "   |-- ex_model_Ar_P_MLJ_NEIGH_RVEC_F"   \
       "   |-- ex_model_Ar_P_Morse"              \
       "   |"
echo ""
echo "NOTE: Only four examples are executed here because all other permutations produce identical results"
echo ""
divider "ex_test_Ar_multiple_models --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F -and- ex_model_Ar_P_MLJ_C"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F ex_model_Ar_P_MLJ_C | ./ex_test_Ar_multiple_models/ex_test_Ar_multiple_models >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_multiple_models --- ex_model_Ar_P_MLJ_C -and- ex_model_Ar_P_LJ"
echo ex_model_Ar_P_MLJ_C ex_model_Ar_P_LJ                 | ./ex_test_Ar_multiple_models/ex_test_Ar_multiple_models >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_multiple_models --- ex_model_Ar_P_MLJ_C -and- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_MLJ_C ex_model_Ar_P_Morse              | ./ex_test_Ar_multiple_models/ex_test_Ar_multiple_models >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ar_multiple_models --- ex_model_Ar_P_LJ -and- ex_model_Ar_P_Morse"
echo ex_model_Ar_P_LJ ex_model_Ar_P_Morse                 | ./ex_test_Ar_multiple_models/ex_test_Ar_multiple_models >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Cu_free_cluster"                 \
       "   |"                                    \
       "   |-- ex_model_Cu_PF_Johnson"           \
       "   |"

divider "ex_test_Cu_free_cluster --- ex_model_Cu_PF_Johnson"
echo ex_model_Cu_PF_Johnson  | ./ex_test_Cu_free_cluster/ex_test_Cu_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ne_free_cluster"                 \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- ex_model_Ne_P_fastLJ"             \
       "   |-- ex_model_Ne_P_LJ"                 \
       "   |-- ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F" \
       "   |-- ex_model_Ne_P_Morse"              \
       "   |"

divider "ex_test_Ne_free_cluster --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F  | ./ex_test_Ne_free_cluster/ex_test_Ne_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster --- ex_model_Ne_P_fastLJ"
echo ex_model_Ne_P_fastLJ              | ./ex_test_Ne_free_cluster/ex_test_Ne_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster --- ex_model_Ne_P_LJ"
echo ex_model_Ne_P_LJ                  | ./ex_test_Ne_free_cluster/ex_test_Ne_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster --- ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F"
echo ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F  | ./ex_test_Ne_free_cluster/ex_test_Ne_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster --- ex_model_Ne_P_Morse"
echo ex_model_Ne_P_Morse               | ./ex_test_Ne_free_cluster/ex_test_Ne_free_cluster >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ne_free_cluster_SI"              \
       "   |"                                    \
       "   |-- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F" \
       "   |-- ex_model_Ne_P_fastLJ"             \
       "   |-- ex_model_Ne_P_LJ"                 \
       "   |-- ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F" \
       "   |-- ex_model_Ne_P_Morse"              \
       "   |"

divider "ex_test_Ne_free_cluster_SI --- ex_model_ArNe_P_MLJ_NEIGH_RVEC_F --- THIS SHOULD FAIL"
echo ex_model_ArNe_P_MLJ_NEIGH_RVEC_F  | ./ex_test_Ne_free_cluster_SI/ex_test_Ne_free_cluster_SI >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster_SI --- ex_model_Ne_P_fastLJ"
echo ex_model_Ne_P_fastLJ              | ./ex_test_Ne_free_cluster_SI/ex_test_Ne_free_cluster_SI >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster_SI --- ex_model_Ne_P_LJ"
echo ex_model_Ne_P_LJ                  | ./ex_test_Ne_free_cluster_SI/ex_test_Ne_free_cluster_SI >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster_SI --- ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F --- THIS SHOULD FAIL"
echo ex_model_Ne_P_MLJ_NEIGH_RVEC_H_F  | ./ex_test_Ne_free_cluster_SI/ex_test_Ne_free_cluster_SI >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster_SI --- ex_model_Ne_P_Morse"
echo ex_model_Ne_P_Morse               | ./ex_test_Ne_free_cluster_SI/ex_test_Ne_free_cluster_SI >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer

#---------------------------------------------------------------------------------------------------------------
header "ex_test_Ne_free_cluster_stiff"           \
       "   |"                                    \
       "   |-- ex_model_Ne_P_LJ"                 \
       "   |-- ex_model_Ne_P_Morse"              \
       "   |"

divider "ex_test_Ne_free_cluster_stiff --- ex_model_Ne_P_LJ"
echo ex_model_Ne_P_LJ                  | ./ex_test_Ne_free_cluster_stiff/ex_test_Ne_free_cluster_stiff >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))

divider "ex_test_Ne_free_cluster_stiff --- ex_model_Ne_P_Morse"
echo ex_model_Ne_P_Morse               | ./ex_test_Ne_free_cluster_stiff/ex_test_Ne_free_cluster_stiff >&$redirect && MODEL_NUM=$(($MODEL_NUM + 1))
footer
