#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2012, Regents of the University of Minnesota.  All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#

#
# Release: This file is part of the openkim-api.git repository.
#


# usage: run_forces_numer_deriv_for_all_models
#
# This script runs the vc_forces_numer_deriv executable for each Model in the
# MODELs directory.  It filters the output so that, for each Model, the Model
# name is printed and followed by a list of supported NBC methods and the
# associated "alpha" value computed by the vc_forces_numer_deriv computation.
# This provides a convenient summary of the results.
# 
#

for mdl in `find ../MODELs -mindepth 1 -maxdepth 1 -type d`
do
   echo $mdl
   echo `basename $mdl` | vc_forces_numer_deriv/vc_forces_numer_deriv | grep -E '(^alpha|NBC Method)' | sed -e 'N' -e 's/.*= *\([^ ]*\).*\n/\1  \t/' -e 's/alpha.*= *\([^ ]*\).*/\1/'
   echo
done
