/*                                                                            */
/* CDDL HEADER START                                                          */
/*                                                                            */
/* The contents of this file are subject to the terms of the Common           */
/* Development and Distribution License Version 1.0 (the "License").          */
/*                                                                            */
/* You can obtain a copy of the license at                                    */
/* http://www.opensource.org/licenses/CDDL-1.0.  See the License for the      */
/* specific language governing permissions and limitations under the License. */
/*                                                                            */
/* When distributing Covered Code, include this CDDL HEADER in each file and  */
/* include the License file in a prominent location with the name             */
/* LICENSE.CDDL.                                                              */
/* If applicable, add the following below this CDDL HEADER, with the fields   */
/* enclosed by brackets "[]" replaced with your own identifying information:  */
/*                                                                            */
/* Portions Copyright (c) [yyyy] [name of copyright owner].                   */
/* All rights reserved.                                                       */
/*                                                                            */
/* CDDL HEADER END                                                            */
/*                                                                            */

/*                                                                            */
/* Copyright (c) 2016--2019, Regents of the University of Minnesota.          */
/* All rights reserved.                                                       */
/*                                                                            */
/* Contributors:                                                              */
/*    Ryan S. Elliott                                                         */
/*                                                                            */

/*                                                                            */
/* Release: This file is part of the kim-api-v2-2.0.1 package.                */
/*                                                                            */


#ifndef KIM_COMPUTE_ARGUMENT_NAME_INC_
#define KIM_COMPUTE_ARGUMENT_NAME_INC_

#define ID_numberOfParticles 0
#define ID_particleSpeciesCodes 1
#define ID_particleContributing 2
#define ID_coordinates 3
#define ID_partialEnergy 4
#define ID_partialForces 5
#define ID_partialParticleEnergy 6
#define ID_partialVirial 7
#define ID_partialParticleVirial 8

#endif /* KIM_COMPUTE_ARGUMENT_NAME_INC_ */
