#!/bin/sh

packagename=$1

# check for errors

if [[ "$packagename" == "" ]]; then
  echo "usage: $0 packagename"
  exit
fi

if [[ -e $packagename ]]; then
  echo "File '$packagename' exits! exiting..."
  exit
fi

# DO IT

git clone . $packagename

cd $packagename

versionfile=openkim-api.version.info
echo "This package ($packagename) created from commit"                               >  $versionfile
echo ""                                                                              >> $versionfile
git rev-parse HEAD                                                                   >> $versionfile
echo ""                                                                              >> $versionfile
echo "of the openkim-api git repository"                                             >> $versionfile
echo "By `git config user.name` (`git config user.email`) on `date`."                >> $versionfile

rm -rf '.git'

cd EXAMPLE_LEGOS

make

cd ..

mv 'DOCs/openkim-api-introduction.pdf' "DOCs/$packagename-introduction.pdf"

rm -rf 'EXAMPLE_LEGOS'

rm -f README_GIT
rm -f create_package
rm -f 'DOCs/openkim-api-introduction.pptx'
rm -f `find . -name ".gitignore"`

cd ..

tar czvf $packagename.tgz $packagename

rm -rf "$packagename"

