#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2013, Regents of the University of Minnesota.
# All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#


packagename=$1

# check for errors

if test X"$packagename" == X""; then
  echo "usage: $0 packagename"
  exit
fi

if test -e $packagename; then
  echo "File '$packagename' exits! exiting..."
  exit
fi

# DO IT

git clone . $packagename

cd $packagename

versionfile=openkim-api.version.info
echo "This package ($packagename) created from commit"                               >  $versionfile
echo ""                                                                              >> $versionfile
git rev-parse HEAD                                                                   >> $versionfile
echo ""                                                                              >> $versionfile
echo "of the openkim-api git repository"                                             >> $versionfile
echo "By `git config user.name` (`git config user.email`) on `date`."                >> $versionfile

rm -rf '.git'

cd EXAMPLE_LEGOS

make

cd ..

mv 'DOCs/openkim-api-introduction.pdf' "DOCs/$packagename-introduction.pdf"

rm -rf 'EXAMPLE_LEGOS'

rm -f README_GIT
rm -f create_package
rm -f 'DOCs/openkim-api-introduction.pptx'
rm -f `find . -name ".gitignore"`

for fl in `grep -l -r "openkim-api\.git repository" *`; do
   ed $fl <<EOF
,s/openkim-api\.git repository/$packagename package/g
w
EOF
done

ed MAKE_SYSTEM/Makefile.LoadDefaults <<EOF
,s/^ *package_name *=.*/package_name = $packagename/
w
EOF

cd ..

tar czvf $packagename.tgz $packagename

rm -rf "$packagename"

