#                                                                      
# Copyright 2011 Ellad B. Tadmor, Ryan S. Elliott, and James P. Sethna 
# All rights reserved.                                                 
#                                                                     
# Author: Valeriu Smirichinski                                         
#
# This is make file has to be included by main makefiles in 
# the KIM_API, MODELs/*/ and TESTs/*/ directories.
# It contains definition for the GNU and Intel compiler sets. 
# It also contains definitions for patern compiling rules.
# 

# NO_FORTRAN=1

# The following line needs to be changed to point to the location of
# the KIMdevel directory:
#KIM_DIR =/Users/sethna/Desktop/KIMdevel/KIMdevel_Patch/
#KIM_DIR =$(HOME)/KIMdevel/

KIM_API_DIR =$(KIM_DIR)KIM_API/
KIM_MODELS_DIR=$(KIM_DIR)MODELs/
KIM_TESTS_DIR=$(KIM_DIR)TESTs/

# All Model .o files and library definitions
# (In the future, this will be generated by the processing pipeline)
MODELOBJ =
ifdef NO_FORTRAN
else
MODELOBJ += $(KIM_MODELS_DIR)Sample_01_lj_cutoff/LJ_mod.o
endif
MODELOBJ += $(KIM_MODELS_DIR)Sample_01_lj_cutoff_c/LJ_sample1.o
MODELOBJ += $(KIM_MODELS_DIR)Sample_01_lj_cutoff_cpp/LJ_sample1.o

# Determine whether a 32 bit or 64 bit compile should be used
# export SYSTEM32="YES"
ifdef SYSTEM32
MACHINESYSTEM=SYSTEM32
else
MACHINESYSTEM=SYSTEM64
endif
ifdef INTEL

# Define Intel compiler switches
OBJONLY=-c
OUTPUTIN=-o
FORTRANFLAG =-module $(KIM_API_DIR) -D $(MACHINESYSTEM) #-nofor_main
CCOMPILER = icc
CPPCOMPILER = icpc
CPPFLAG = -O3 -I$(KIM_API_DIR)
CPPLIBFLAG = -nofor_main -cxxlib
FORTRANLIBFLAG = -cxxlib
FORTRANCOMPILER = ifort
LINKCOMPILER = $(FORTRANCOMPILER)
else

# Define GNU compiler switches
OBJONLY=-c
OUTPUTIN=-o
FORTRANFLAG = -fcray-pointer -O3 -J$(KIM_API_DIR) -D $(MACHINESYSTEM)
CCOMPILER = gcc
CPPCOMPILER = g++
#
CPPFLAG = -O3 -I$(KIM_API_DIR)
FORTRANCOMPILER = gfortran
#CPPLIBFLAG = -lgfortran       #if GNU version 4.5 and up. tested on suse 
#LINKCOMPILER = $(CPPCOMPILER) #if GNU version 4.5 and up. tested on suse
CPPLIBFLAG = -lstdc++             #if GNU version 4.4.1. tested on suse
LINKCOMPILER = $(FORTRANCOMPILER) #if GNU version 4.4.1. tested on suse
#ifdef NO_FORTRAN
#CPPLIBFLAG =
#FORTRANCOMPILER = echo No fortran compiler
#endif
endif

# Definition of c and fortran .o file list
OBJC = $(KIM_API_DIR)KIMserviceC.o  $(KIM_API_DIR)KIMservice.o
ifdef NO_FORTRAN
OBJF90 =
else
OBJF90 =$(KIM_API_DIR)KIMserviceF.o
endif
ALLOBJ = $(OBJC) $(OBJF90)

# Compiler pattern rules
%.o:%.c
	$(CCOMPILER) $(CPPFLAG) $(OBJONLY) $<
%.o:%.cpp
	$(CPPCOMPILER) $(CPPFLAG) $(OBJONLY) $<
%.o:%.f90
	$(FORTRANCOMPILER) $(FORTRANFLAG) $(OBJONLY) $<
%.o:%.F90
	$(FORTRANCOMPILER) $(FORTRANFLAG) $(OBJONLY) $<


