
ifndef KIM_API_DIR
include ../../KIM_API/Include.mk
else
include $(KIM_API_DIR)Include.mk
endif

all: model_EAM_periodic_aluminum_ercolessi_adams.a

model_EAM_periodic_aluminum_ercolessi_adams.a: model_EAM_periodic_aluminum_ercolessi_adams.o
	@ar rcs $@ *.o

clean:
	rm -f *.o *.mod *.a

