
#                                                                      
# Copyright 2011 Ellad B. Tadmor, Ryan S. Elliott, and James P. Sethna 
# All rights reserved.                                                 
#                                    
# Author: Ryan S. Elliott
#
# 
# this make file builds/cleans the example models and tests
#
#

.PHONY: all

all: 
	$(MAKE) -C $(KIM_DIR)EXAMPLE_LEGOS/model_legos all
	@echo
	$(MAKE) -C $(KIM_DIR)EXAMPLE_LEGOS/test_legos  all
