#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2013--2019, Regents of the University of Minnesota.
# All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#

#
# Release: This file is part of the kim-api-2.1.0 package.
#


# goto the top level repo directory
if THE_GIT_DIR="`git rev-parse --show-toplevel 2> /dev/null`"; then
  cd "${THE_GIT_DIR}"
fi

files=`find .    -name "*.hpp"     \
              -o -name "*.hpp.in"  \
              -o -name "*.cpp"     \
              -o -name "*.cpp.in"  \
              -o -name "*.inc"     \
              -o -name "*.inc.in"  \
              -o -name "*.h"       \
              -o -name "*.h.in"    \
              -o -name "*.c"       \
              -o -name "*.c.in"`

printf "Executing clang-format on all c/c++ files in directory ${PWD}.\n"

clang-format -style=file -i ${files}
