#!/bin/sh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2013--2020, Regents of the University of Minnesota.
# All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#

#
# Release: This file is part of the kim-api-2.2.1 package.
#


printf -- "\n"
printf -- "The git-hooks expect the system to have:\n"
printf -- "  * clang-format\n"
printf -- "  * fprettify\n"
printf -- "installed and on the PATH.\n"
printf -- "\n"
printf -- "  To install clang-foramt, use a package manager\n"
printf -- "  such as homebrew:\n"
printf -- "\n"
printf -- "    %% brew install clang-format\n"
printf -- "\n"
printf -- "  To create fprettify virtualenv perform the following\n"
printf -- "  in the directory of your choice.\n"
printf -- "\n"
printf -- "    %% virtualenv fprettify\n"
printf -- "    %% souce fprettify/bin/activate\n"
printf -- "    %% pip install —upgrade fprettify\n"
printf -- "\n"
printf -- "  Then add a shell script, say to \${HOME}/bin, for running fprettify.\n"
printf -- "\n"

# set hooksPath to repo local hooks directory
git config --local core.hooksPath git-hooks
