#!/bin/sh

#
# KIM-API: An API for interatomic models
# Copyright (c) 2013--2022, Regents of the University of Minnesota.
# All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

#
# Release: This file is part of the kim-api-2.3.0 package.
#


printf -- "\n"
printf -- "The git-hooks expect the system to have:\n"
printf -- "  * clang-format\n"
printf -- "  * fprettify\n"
printf -- "installed and on the PATH.\n"
printf -- "\n"
printf -- "  To install clang-foramt, use a package manager\n"
printf -- "  such as homebrew:\n"
printf -- "\n"
printf -- "    %% brew install clang-format\n"
printf -- "\n"
printf -- "  To create fprettify virtualenv perform the following\n"
printf -- "  in the directory of your choice.\n"
printf -- "\n"
printf -- "    %% virtualenv fprettify\n"
printf -- "    %% souce fprettify/bin/activate\n"
printf -- "    %% pip install —upgrade fprettify\n"
printf -- "\n"
printf -- "  Then add a shell script, say to \${HOME}/bin, for running fprettify.\n"
printf -- "\n"

# set hooksPath to repo local hooks directory
git config --local core.hooksPath git-hooks
