    !-- KIM variables
    integer numberOfParticles;        pointer(pnAtoms,numberOfParticles)
    integer nparticleTypes;           pointer(pnparticleTypes,nparticleTypes)
    integer particleTypes(1);         pointer(pparticleTypes,particleTypes)
    double precision model_cutoff;    pointer(pcutoff,model_cutoff)
    double precision model_epsilon;   pointer(pepsilon,model_epsilon)
    double precision model_sigma;     pointer(psigma,model_sigma)
    double precision model_cutnorm;   pointer(pcutnorm,model_cutnorm)
    double precision model_A;         pointer(pA,model_A)
    double precision model_B;         pointer(pB,model_B)
    double precision model_C;         pointer(pC,model_C)
    double precision model_sigmasq;   pointer(psigmasq,model_sigmasq)
    double precision model_cutsq;     pointer(pcutsq,model_cutsq)
    double precision energy;          pointer(penergy,energy)
    double precision coordum(DIM,1);  pointer(pcoor,coordum)
    double precision forcedum(DIM,1); pointer(pforce,forcedum)
    double precision enepotdum(1);    pointer(penepot,enepotdum)
    double precision virialdum(1);    pointer(pvirial,virialdum)
    double precision, pointer :: coor(:,:),force(:,:),ene_pot(:),virial_global(:)
    integer comp_energy, comp_force, comp_enepot, comp_virial
