!*******************************************************************************
!**
!**  MODULE MODEL_NAME_STR
!**
!**  Lennard-Jones pair potential model for argon 
!**  (modified to have smooth cutoff)
!**
!**  Author: automatically generated by the openkim-api make system
!**
!**  Copyright 2011 Ellad B. Tadmor, Ryan S. Elliott, and James P. Sethna
!**  All rights reserved.
!**
!*******************************************************************************

module MODEL_NAME_STR
  use KIMservice
  implicit none


  save
  private
  public Compute_Energy_Forces
  public ReInit
  public Destroy
  public report_error
  
contains
  
!-------------------------------------------------------------------------------
!
! Compute energy and forces on atoms from the positions.
!
!-------------------------------------------------------------------------------
  subroutine Compute_Energy_Forces(pkim,ier)
    implicit none

    !-- Transferred variables
    integer(kind=kim_intptr), intent(in)  :: pkim
    integer,                  intent(out) :: ier
    
    !-- Local variables
    integer, parameter :: DIM=3
    double precision :: r,Rsqij,phi,dphi,d2phi
