#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License Version 1.0 (the "License").
#
# You can obtain a copy of the license at
# http://www.opensource.org/licenses/CDDL-1.0.  See the License for the
# specific language governing permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each file and
# include the License file in a prominent location with the name LICENSE.CDDL.
# If applicable, add the following below this CDDL HEADER, with the fields
# enclosed by brackets "[]" replaced with your own identifying information:
#
# Portions Copyright (c) [yyyy] [name of copyright owner]. All rights reserved.
#
# CDDL HEADER END
#

#
# Copyright (c) 2013--2014, Regents of the University of Minnesota.
# All rights reserved.
#
# Contributors:
#    Ryan S. Elliott
#

#
# Release: This file is part of the openkim-api.git repository.
#


# sanity checks
ifndef KIM_DIR
   $(error Make variable KIM_DIR must be defined.)
endif
include $(KIM_DIR)/MAKE_SYSTEM/Makefile.SanityCheck

# Clean up variables
TEST_NAME := $(strip $(TEST_NAME))

all: $(TEST_NAME)

$(TEST_NAME): $(TEST_NAME).o $(LOCALOBJ) $(KIMLIBFULLFILE)
	@printf "Creating... Test executable... $@.\n"
	$(QUELL)$(LD) $(ARCHFLAG) $(KIMLIBFLAGS) $(LDFLAGS) $(LOCALOBJ) $< $(KIMLIB) $(XLANGLDLIBS) $(LDDYNAMICLIB) $(LDLIBS) $(OUTPUTINFLAG) $@

$(TEST_NAME).o: $(LOCALOBJ) Makefile

Makefile: $(KIM_MAKE_FILES) $(KIM_DIR)/MAKE_SYSTEM/Makefile.Test
	$(QUELL)touch Makefile

clean:
	@printf "Cleaning... Test........... $(TEST_NAME).\n"
	$(QUELL)rm -f *.mod $(LOCALOBJ) $(TEST_NAME).o $(TEST_NAME) $(LOCAL_CLEAN)
